export const postActionTypes = {
    GET_ALL_POST: 'GET_ALL_POST',
    CREATE_NEW_POST: 'CREATE_NEW_POST',
    UPDATE_POST_DATA: 'UPDATE_POST_DATA',
    DELETE_POST_DATA: 'DELETE_POST_DATA',
    UPDATE_POST_LIKE: 'UPDATE_POST_LIKE',
    UPDATE_POST_DISLIKE: 'UPDATE_POST_DISLIKE'
};